development:
  adapter: mysql
  database: ihponrails_development
  username: root
  password:

test:
  adapter: mysql
  database: ihponrails_test
  username: root
  password:

production:
  adapter: mysql
  database: ihponrails
  username: root
  password:
